FROM ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -y bash cmake g++

WORKDIR /Minuit2
ADD https://github.com/GooFit/Minuit2/archive/refs/tags/v6-24-00.tar.gz /Minuit2
RUN gunzip -c v6-24-00.tar.gz | tar -xf -
RUN mkdir Minuit2-6-24-00/build && cd Minuit2-6-24-00/build && cmake .. && make

# docker build . -f Dockerfile-Minuit2 -t minuit2
# docker run -it --name Minuit2 minuit2